version: "2"

services:
 manager:
  build: .
  ports:
   - "8080:8080"
  volumes:
   - "./tmp/mt-mgr-data:/data"
   - "/var/run/docker.sock:/var/run/docker.sock"
  environment:
   INSTANCE_NAME: dummy
   HOST_DATA_DIR: /tmp/mt-mgr-data
