name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: buckaroobanzay/minetest_manager
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true

    - name: Update pandorabox deployment
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: pandorabox-io/pandorabox.io
        event-type: update_deployment
