name: jshint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: apt
      run: sudo apt-get install -y nodejs npm

    - name: npm install
      run: npm ci

    - name: jshint backend run
      run: npm run jshint_backend

    - name: jshint frontend run
      run: npm run jshint_frontend
